### ISSUE TITLE
Assigning array to a draft always produced new instance

### ISSUE THREAD

**Issue by travikk** [mweststrate/immer#150] opened 2018-05-07 06:02 UTC
Hey,

Given the following code:

```
import produce from "immer";

const items = [{ id: "1", name: "travikk" }, { id: "2", name: "immer" }];

const baseState = {
  loading: false,
  items
};

const booleanChanged = produce(baseState, draft => {
  draft.loading = true;
});

const nameChanged = produce(baseState, draft => {
  draft.items[0].name = "travikk";
});

const arrayAssigned = produce(baseState, draft => {
  draft.items = items.concat();
});

console.log('*** When bool changed');
console.log('Whole state equality:', baseState === booleanChanged); // returns false, 
console.log('Arrat equality:', baseState.items === booleanChanged.items); // returns true

console.log('*** When name set to same name');
console.log('Whole state equality:', baseState === nameChanged); // returns true
console.log('Arrat equality:', baseState.items === nameChanged.items); // returns true

console.log('*** When array cloned');
console.log('Whole state equality:', baseState === arrayAssigned); // returns false
console.log('Arrat equality:', baseState.items === arrayAssigned.items); // returns false
```

Equality checck agains nameChanged will return true, as it's setting name to the same value as the baseState.
Equality check against arrayAssigned will return false (both for the state and state.items). 
This to me looks like it should return true, as we're not modyfing the _underlaying_ data. 

Here's a code sandbox link with the above code:

https://codesandbox.io/s/wkm6j5m74l

**Comment by mweststrate** [comment] 2018-05-28 07:05
Closing as answer has been provided and this is working as intended

**Closed** 2018-05-28 07:04 UTC
