### ISSUE TITLE
reference equality not preserved within draft

### ISSUE THREAD

**Issue by rymohr** [mweststrate/immer#175] opened 2018-08-16 21:19 UTC
Been loving this library in combination with redux but just ran into a surprising behavior. In the example below I expected `data1` and `data2` to point to the same draft.

https://codesandbox.io/s/qkrq9qy7v6

Version 1.5.0 with and without proxies.

**Comment by mweststrate** [comment] 2018-08-23 09:56
Duplicate of #174

**Closed by mweststrate** 2018-08-23 09:56 UTC
