### ISSUE TITLE
Cannot import from immer with webpack 4

### ISSUE THREAD

**Issue by erango** [mweststrate/immer#333] opened 2019-03-13 09:42 UTC
## 🐛 Bug Report

When importing immer to React with Webpack 4, I get this exception:
`Error was not caught ReferenceError: require is not defined
    at Module.../node_modules/immer/dist/immer.mjs (immer.mjs:1066)`

## To Reproduce

Use a react + webpack 4 setup, such as the default create-react-app setup.

## Expected behavior

Import should work.

## Environment

-   **Immer version: 2.1.2**
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by egoist** [comment] 2019-03-13 09:55
Related: https://github.com/mweststrate/immer/issues/331#issuecomment-472299725

However I can't reproduce this using CRA and the [example code](https://github.com/mweststrate/immer#example).

**Comment by mweststrate** [comment] 2019-03-13 10:38
Fun fact: there is not a single 'require' (or import for that matter)
statement in 'immer.mjs'....

Make sure to at least upgrade webpack to the latest version of 4, as there
has been some bugs with this in the past, for example:
https://github.com/webpack/webpack/issues/8491

**Comment by erango** [comment] 2019-03-13 10:40
Thanks for the lightning fast response guys! I'll keep you posted

**Comment by mohsinulhaq** [comment] 2019-03-13 13:01
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L507

CRA works because of above config
I tried removing mjs from here
build with 2.1.2 fails, while 2.1.3 works

so, for me, https://github.com/mweststrate/immer/issues/331#issuecomment-472299725
it failed because we aren't taking care of mjs files in webpack

**Comment by mweststrate** [comment] 2019-03-18 08:28
Since it seems fixed with 2.1.3, I think we can close this issue? Could you confirm @erango?

**Comment by erango** [comment] 2019-03-18 15:31
Yes 😄  Thanks everyone!

**Closed** 2019-03-18 15:32 UTC
Labels: bug
