### ISSUE TITLE
Using Destructuring failure

### ISSUE THREAD

**Issue by yuanalexwu** [mweststrate/immer#94] opened 2018-02-10 08:46 UTC
```javascript
const baseState = {
  foo: 'aaaa',
  bar: 'bbbb',
}
const updateData = {
  bar: 'cccc',
}
const newState = produce(baseState, draft => {
  draft = { ...draft, ...updateData }
})
console.log(newState)
// newState {foo: 'aaaa', ar: 'bbbb'}
```

the newState doesn't change

**Comment by mweststrate** [comment] 2018-02-10 11:55
The problem is that you are reassigning draft, which doesn't modify the
original draft but just creates a local variable which is further not used
anywhere. You can use Object.assign(draft, updateData) though

Op za 10 feb. 2018 09:46 schreef sam <notifications@github.com>:

**Comment by yuanalexwu** [comment] 2018-02-11 08:59
Thx for ur reply
I just a little bit lazy, normally we should update like below:
```javascript
const baseState = {
  foo: 'aaaa',
  bar: 'bbbb',
}
const updateData = {
  bar: 'cccc',
}
const newState = produce(baseState, draft => {
  draft.bar = updateData.bar //  <---------------- mark
})
```
The line I marked update a single property. What if I got many properties to be updated
It must be assigned one by one

**Comment by benbraou** [comment] 2018-02-11 23:58
@yuanalexwu you can use [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) as suggested by @mweststrate 
`Object.assign(draft, updateData)` will mutate `draft` by copying the enumerable properties from `updateData`.
Checkout this example: 
```typescript
const base = {a: 1, b: 2, c: 3, d: 4};
const obj = new Proxy(base, {
	set: function(obj, prop, value) {
		console.log(`current property: ${prop}`);
		obj[prop] = value;
		return true;
    }
})
const update = {a: 11, b: 22, c: 33, d: 44};
Object.assign(obj, update);
```
The following will be logged into console:
```
current property: a
current property: b
current property: c
current property: d
```
Also, please note that`draft` is a proxy on the `baseState`. `Immer` defines`Proxy ` traps that will be used to build the new state based on the mutation you make on the`draft `

**Closed** 2018-02-11 23:59 UTC
Labels: question

**Comment by Grsmto** [comment] 2018-05-28 16:49
Hey guys,
Sorry to pop on this issue but I'm not sure I'm facing a bug or I just don't understand how Immer works.
It seems like once we use `Object.assign` like suggested in #issuecomment-364646429 I got a `read only` error. You can find an example on the following codesandbox https://codesandbox.io/s/mzx4w93wx9 .

Does anyone has an idea if I'm doing something wrong there or if it's a bug?
Thanks!

**Comment by mweststrate** [comment] 2018-05-28 22:00
Please avoid commenting on closed issues, rather open new one referring to
this

Op ma 28 mei 2018 18:49 schreef Adrien Denat <notifications@github.com>:
